### ISSUE TITLE
Executed repeatedly when both Describer and Evaluator are declared

### ISSUE THREAD

**Issue by matheme-justyn** [nics-tw/PETsARD#351]
Describer 與 Evaluator 並列時，在 Config 上會產生 sequence 層級關係，導致重複執行

- 這會導致後面宣告的 Describer/Evaluator 會抓不到來源。參考以下例子：

```yaml
Postprocessor:
      default-sdv:
        method: 'default'
Evaluator:
    sdmetrics-diag:
        method: 'sdmetrics-diagnosticreport'
Describer:
    desc:
        method: 'default'
```

這時候 Describer 會報錯
AttributeError: 'dict' object has no attribute 'shape'
是因為他抓的 input 是 Evaluator 的 get_result()，而非預期的 Postprocessor

我傾向想在 Config 這一層，用某種方法定義 Describer 跟 Evaluator 是同一種東西
