### ISSUE TITLE
DescriberOperator - Multiple source and support Splitter

### ISSUE THREAD

**Issue by matheme-justyn** [nics-tw/PETsARD#371]
- 在 DescriberOperator 中，目前自動抓的是 status 的前一個模組的輸出

```Python
            self.input['data'] = {
                'data': status.get_result(status.get_pre_module('Describer'))
            }
```
    - 由於 Splitter 的輸出是 dict，這使得抓 Splitter 成為不可能。但為了確認我們抽樣的偏誤，描述 Splitter 的結果這個需求我很希望添加
    - 另外由於同一個 YAML 裡面只能用同一個模組一次，這使得沒辦法寫出同時對 Loader, Postprocessor 等多個資料結果做描述

同時可參考 demo/dev/Issue371.ipynb

目前我想到的是在 DescriberOperator 仿造 Reporter 做個 source (str)，指定要描述哪一個模組/實驗名稱
- Splitter 就可以利用這功能寫成 Splitter_[train]，仿造 Reporter save_report 的格式
- 另外用 source 這個名稱，可能會想到 Reporter save_data 的 source，代表我們除了支援第一種分開實驗寫的做法，還支援第二種 source 為 List[str]，這可能使得 Reporter 的 save_report 在抓取 eval = 'desc' 的時候可能會取得多個報告...
    - 看要趁機統一，DescriberOperator, save_data, save_report 統一都叫 source，只是每個支援 str 或 List[str] 不同
    - 還是仿造 save_report，改叫 desc 來描述，Reporter 的 save_report 直接全部 granularity 符合的都疊在一起也 OK

```YAML
# demo 1
Describer:
    desc-loader:
        method: default
        source: Loader
    desc-postproc:
        method: default
        source: Postprocessor

# demo 2
Describer:
    desc:
        method: default
        source:
            - Loader
            - Postprocessor
```

CC @mileschangmoda ，這屬於新 spec 的一環，先寫下來
