### ISSUE TITLE
Reporter: handle no assign granularity report on first trials

### ISSUE THREAD

**Issue by matheme-justyn** [nics-tw/PETsARD#419]
在 YAML 當中同時寫兩個 Reporter 去取不同的顆粒度 (granularity) 的時候，會在第一輪遇到下面這個錯誤。例如以下 YAML 與錯誤：

```
Reporter:
    save_report_global:
        method: 'save_report'
        output: '20240328_exp6'
        granularity: 'global'
    save_report_columnwise:
        method: 'save_report'
        output: '20240328_exp6'
        granularity: 'columnwise'
```

```Python
File [...\PETsARD\PETsARD\reporter\reporter.py:644](.../PETsARD/PETsARD/reporter/reporter.py:644), in ReporterSaveReport.report(self)
    [642](.../PETsARD/PETsARD/reporter/reporter.py:642) print(self.result)
    [643](.../PETsARD/PETsARD/reporter/reporter.py:643) if 'Reporter' not in self.result:
--> [644](.../PETsARD/PETsARD/reporter/reporter.py:644)     raise UnexecutedError
    [646](.../PETsARD/PETsARD/reporter/reporter.py:646) if 'eval_expt_name' not in self.result['Reporter']:
    [647](.../PETsARD/PETsARD/reporter/reporter.py:647)     # no {granularity} granularity report in {eval}
    [648](.../PETsARD/PETsARD/reporter/reporter.py:648)     return

UnexecutedError:
```

這是由於 `ReporterSaveReport` 對於 `ReporterSaveReporter.create()` 在讀取到沒有指定的顆粒度的時候，僅彈出警告而沒有寫東西進 `ReportSaveReporter.result`，從而讓 `ReporterSaveReport.report()` 無法分辨是真的未執行、還是沒有指定顆粒度，而誤觸防未執行告警所導致。解決方法可能是導入類似狀態碼的功能

```Python
        # 3. match granularity, if exist, copy()
        if report is None:
            print(
                f"Reporter: "
                f"There's no {granularity} granularity report "
                f"in {full_expt_tuple[-2]}. "
                f"Nothing collect."
            )
            return True, None
        report = report.copy()
```

```Python
    def report(self) -> None:
        """
        Generates a report based on the provided report data.
            The report is saved to the specified output location.
        """
        if 'Reporter' not in self.result:
            raise UnexecutedError

        if 'eval_expt_name' not in self.result['Reporter']:
            # no {granularity} granularity report in {eval}
            return
```
