### ISSUE TITLE
Processor - customized-able on YAML

### ISSUE THREAD

**Issue by matheme-justyn** [nics-tw/PETsARD#673]
從 #671 來的，現在的自訂程度不太理想

- 只想執行 missing:
  - 可以這麼設
  ```yaml
  Preprocessor:
    missing-only:
      sequence:
        - 'missing'
  ```
- 改變說數值型用 mode -> 不友善，需要全部欄位名稱正面表列
- 要自訂某些欄位
  - 現在都要設 config，我覺得跟 Describer 現在的設計一樣不直覺：我的 parameter 不就是 config 了，為啥我還要再包一層叫 config 的東西？
  ```yaml
    missing-custom:
      method: 'default' # other kept as default
      config:
        missing:
          # drop missing value in 'workclass' as default
          workclass: 'missing_drop'
          # mode imputation for missing value in 'occupation'
          occupation: 'missing_mode'
          # custom imputation 'Taiwan' for missing value in 'native-country'
          native-country:
            method: 'missing-simple'
            value: 'Taiwan'
  ```

希望能面向一般人（不考慮任何使用 python class Processor 的情況）來優化 API
